// カラム構成: role(ロール定数), name(ヒーロー名), jp_name(ヒーロー和名)
// ロール定数: 'ATTACKER', 'GUNNER', 'SPRINTER', 'TANK'
const LIST_HERO = [

    { role: 'ATTACKER', name: 'ATTACKER_001', jp_name: '双挽 乃保' },
    { role: 'ATTACKER', name: 'ATTACKER_002', jp_name: '桜華 忠臣' },
    { role: 'ATTACKER', name: 'ATTACKER_003', jp_name: 'マルコス’55' },
    { role: 'ATTACKER', name: 'ATTACKER_004', jp_name: 'マリア=S=レオンブルク' },
    { role: 'ATTACKER', name: 'ATTACKER_005', jp_name: 'アダム=ユーリエフ' },
    { role: 'ATTACKER', name: 'ATTACKER_006', jp_name: 'ソル＝バッドガイ' },
    { role: 'ATTACKER', name: 'ATTACKER_007', jp_name: 'リュウ' },
    { role: 'ATTACKER', name: 'ATTACKER_008', jp_name: 'レム' },
    { role: 'ATTACKER', name: 'ATTACKER_009', jp_name: 'カイ＝キスク' },
    { role: 'ATTACKER', name: 'ATTACKER_010', jp_name: 'ヴィーナス ポロロッチョ' },
    { role: 'ATTACKER', name: 'ATTACKER_011', jp_name: 'リヴァイ' },
    { role: 'ATTACKER', name: 'ATTACKER_012', jp_name: 'デビルミント鬼龍 デルミン' },
    { role: 'ATTACKER', name: 'ATTACKER_013', jp_name: 'セイバーオルタ' },
    { role: 'ATTACKER', name: 'ATTACKER_014', jp_name: 'ルルカ' },
    { role: 'ATTACKER', name: 'ATTACKER_015', jp_name: 'アイズ･ヴァレンシュタイン' },
    { role: 'ATTACKER', name: 'ATTACKER_016', jp_name: '狐ヶ咲 甘色' },
    { role: 'ATTACKER', name: 'ATTACKER_017', jp_name: 'ノクティス' },
    { role: 'ATTACKER', name: 'ATTACKER_018', jp_name: 'イグニス=ウィル=ウィスプ' },
    { role: 'ATTACKER', name: 'ATTACKER_019', jp_name: 'キリト' },
    { role: 'ATTACKER', name: 'ATTACKER_020', jp_name: 'ステリア・ララ・シルワ' },
    { role: 'ATTACKER', name: 'ATTACKER_021', jp_name: 'ヨルハ二号B型' },
    { role: 'ATTACKER', name: 'ATTACKER_022', jp_name: 'リムル=テンペスト' },
    { role: 'ATTACKER', name: 'ATTACKER_023', jp_name: '御坂 美琴' },
    { role: 'ATTACKER', name: 'ATTACKER_024', jp_name: 'クー・シー' },
    { role: 'ATTACKER', name: 'ATTACKER_025', jp_name: 'デンジ' },
    { role: 'ATTACKER', name: 'ATTACKER_026', jp_name: 'ターニャ・デグレチャフ' },
    { role: 'ATTACKER', name: 'ATTACKER_027', jp_name: 'コラプス' },
    { role: 'ATTACKER', name: 'ATTACKER_028', jp_name: 'ボンドルド' },
    { role: 'ATTACKER', name: 'ATTACKER_029', jp_name: 'ゴン' },
    { role: 'ATTACKER', name: 'ATTACKER_030', jp_name: 'シャドウ' },
    { role: 'ATTACKER', name: 'ATTACKER_031', jp_name: 'アーチャー（ギルガメッシュ）' },
    { role: 'GUNNER', name: 'GUNNER_001', jp_name: 'リリカ' },
    { role: 'GUNNER', name: 'GUNNER_002', jp_name: 'ルチアーノ' },
    { role: 'GUNNER', name: 'GUNNER_003', jp_name: '深川 まとい' },
    { role: 'GUNNER', name: 'GUNNER_004', jp_name: '13 †サーティーン†' },
    { role: 'GUNNER', name: 'GUNNER_005', jp_name: 'ディズィー' },
    { role: 'GUNNER', name: 'GUNNER_006', jp_name: 'エミリア' },
    { role: 'GUNNER', name: 'GUNNER_007', jp_name: 'メグメグ' },
    { role: 'GUNNER', name: 'GUNNER_008', jp_name: '鏡音 リン' },
    { role: 'GUNNER', name: 'GUNNER_009', jp_name: 'イスタカ' },
    { role: 'GUNNER', name: 'GUNNER_010', jp_name: 'ソーン=ユーリエフ' },
    { role: 'GUNNER', name: 'GUNNER_011', jp_name: '猫宮 ひなた' },
    { role: 'GUNNER', name: 'GUNNER_012', jp_name: '岡部 倫太郎' },
    { role: 'GUNNER', name: 'GUNNER_013', jp_name: 'ギルガメッシュ' },
    { role: 'GUNNER', name: 'GUNNER_014', jp_name: 'HM-WA100 ニーズヘッグ' },
    { role: 'GUNNER', name: 'GUNNER_015', jp_name: '芥川 龍之介' },
    { role: 'GUNNER', name: 'GUNNER_016', jp_name: 'ゲームバズーカガール' },
    { role: 'GUNNER', name: 'GUNNER_017', jp_name: 'アインズ・ウール・ゴウン' },
    { role: 'GUNNER', name: 'GUNNER_018', jp_name: '糸廻 輪廻' },
    { role: 'GUNNER', name: 'GUNNER_019', jp_name: 'Bugdoll' },
    { role: 'GUNNER', name: 'GUNNER_020', jp_name: 'アクセラレータ' },
    { role: 'GUNNER', name: 'GUNNER_021', jp_name: '天空王 ぶれいずどらごん' },
    { role: 'GUNNER', name: 'GUNNER_022', jp_name: 'ロキシー・ミグルディア' },
    { role: 'GUNNER', name: 'GUNNER_023', jp_name: 'ロックマンEXE＆光熱斗' },
    { role: 'GUNNER', name: 'GUNNER_024', jp_name: 'シノン' },
    { role: 'GUNNER', name: 'GUNNER_025', jp_name: 'みりぽゆ' },
    { role: 'GUNNER', name: 'GUNNER_026', jp_name: 'メルーニャ' },
    { role: 'GUNNER', name: 'GUNNER_027', jp_name: 'ランサー（エルキドゥ）' },
    { role: 'TANK', name: 'TANK_001', jp_name: 'ジャスティス ハンコック' },
    { role: 'TANK', name: 'TANK_002', jp_name: 'ジャンヌ ダルク' },
    { role: 'TANK', name: 'TANK_003', jp_name: 'グスタフ ハイドリヒ' },
    { role: 'TANK', name: 'TANK_004', jp_name: 'ヴィオレッタ ノワール' },
    { role: 'TANK', name: 'TANK_005', jp_name: '鏡音 レン' },
    { role: 'TANK', name: 'TANK_006', jp_name: 'モノクマ' },
    { role: 'TANK', name: 'TANK_007', jp_name: 'めぐみん' },
    { role: 'TANK', name: 'TANK_008', jp_name: 'トマス' },
    { role: 'TANK', name: 'TANK_009', jp_name: '佐藤四郎兵衛忠信' },
    { role: 'TANK', name: 'TANK_010', jp_name: 'ライザリン・シュタウト' },
    { role: 'TANK', name: 'TANK_011', jp_name: '青春 アリス' },
    { role: 'TANK', name: 'TANK_012', jp_name: 'ラヴィ・シュシュマルシュ' },
    { role: 'TANK', name: 'TANK_013', jp_name: 'アミスター=バランディン' },
    { role: 'TANK', name: 'TANK_014', jp_name: '鬼ヶ式うら' },
    { role: 'TANK', name: 'TANK_015', jp_name: 'ポプ子＆ピピ美' },
    { role: 'SPRINTER', name: 'SPRINTER_001', jp_name: '十文字 アタリ' },
    { role: 'SPRINTER', name: 'SPRINTER_002', jp_name: 'Voidoll' },
    { role: 'SPRINTER', name: 'SPRINTER_003', jp_name: 'ニコラ テスラ' },
    { role: 'SPRINTER', name: 'SPRINTER_004', jp_name: 'コクリコット ブランシュ' },
    { role: 'SPRINTER', name: 'SPRINTER_005', jp_name: 'かけだし勇者' },
    { role: 'SPRINTER', name: 'SPRINTER_006', jp_name: '初音 ミク' },
    { role: 'SPRINTER', name: 'SPRINTER_007', jp_name: '春麗' },
    { role: 'SPRINTER', name: 'SPRINTER_008', jp_name: 'ザック & レイチェル' },
    { role: 'SPRINTER', name: 'SPRINTER_009', jp_name: '輝龍院 きらら' },
    { role: 'SPRINTER', name: 'SPRINTER_010', jp_name: 'アクア' },
    { role: 'SPRINTER', name: 'SPRINTER_011', jp_name: '零夜' },
    { role: 'SPRINTER', name: 'SPRINTER_012', jp_name: 'ピエール 77世' },
    { role: 'SPRINTER', name: 'SPRINTER_013', jp_name: '中島 敦' },
    { role: 'SPRINTER', name: 'SPRINTER_014', jp_name: 'ジョーカー' },
    { role: 'SPRINTER', name: 'SPRINTER_015', jp_name: 'アスナ' },
    { role: 'SPRINTER', name: 'SPRINTER_016', jp_name: 'ラム' },
    { role: 'SPRINTER', name: 'SPRINTER_017', jp_name: 'アル･ダハブ=アルカティア' },
    { role: 'SPRINTER', name: 'SPRINTER_018', jp_name: 'ベル･クラネル' },
    { role: 'SPRINTER', name: 'SPRINTER_019', jp_name: '某' },
    { role: 'SPRINTER', name: 'SPRINTER_020', jp_name: 'パワー' },
    { role: 'SPRINTER', name: 'SPRINTER_021', jp_name: 'キルア' },
    { role: 'SPRINTER', name: 'SPRINTER_022', jp_name: 'チーちゃん' },
    { role: 'SPRINTER', name: 'SPRINTER_023', jp_name: '上条当麻' },
    { role: 'SPRINTER', name: 'SPRINTER_024', jp_name: 'ーペルリニエ' },
    { role: 'SPRINTER', name: 'SPRINTER_025', jp_name: 'セイバー（獅子心王リチャード1世）' }
];